declare module '@event-calendar/core'
declare module '@event-calendar/common'
declare module '@event-calendar/time-grid'
declare module '@event-calendar/day-grid'
declare module '@event-calendar/interaction'
declare module '@event-calendar/list'
declare module '@event-calendar/resource-time-grid'
